INSERT INTO samples (content) values ('HELLO WORLD')
INSERT INTO tasks (title) values ('タスク1')
INSERT INTO tasks (title) values ('タスク2')
INSERT INTO tasks (title) values ('タスク3')
INSERT INTO tasks (title) values ('タスク4')
INSERT INTO tasks (title) values ('タスク5')