CREATE TABLE IF NOT EXISTS samples(
    id SERIAL NOT NULL PRIMARY KEY,
    content VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id SERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(256) NOT NULL
);